=== wangyoushun/CompactDb/src/com/six/compactdb/dtd/compactdb-scripts-1.0.dtd
<!-- Compactdb script configuration document.

<!DOCTYPE compactdb-scripts PUBLIC
    "-//compactdb/compactdb Script DTD 1.0//EN"
    "http://www.iwantfly.sh.cn/compactdb-scripts-1.0.dtd" >
-->

<!ELEMENT compactdb-scripts (default?, oracle?, sybase?, mysql?)>
<!ATTLIST compactdb-scripts
	namespace CDATA #REQUIRED
>
<!ELEMENT default (script+)>
<!ELEMENT oracle (script+)>
<!ELEMENT sybase (script+)>
<!ELEMENT mysql (script+)>
<!ELEMENT script (sql, parameters?)>
<!ATTLIST script
	name CDATA #REQUIRED
	isquery (true | false) "true"
>
<!ELEMENT sql (#PCDATA)>
<!ELEMENT parameters (parameter+)>
<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
	name CDATA #REQUIRED
	datatype (string | int | long | date | decimal | binary | cursor) "string"
	type (in | out) "in"
>

=== wangyoushun/CompactDb/test/user.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE compactdb-scripts PUBLIC
    "-//compactdb/compactdb Script DTD 1.0//EN"
    "http://www.iwantfly.sh.cn/compactdb-scripts-1.0.dtd" >
<compactdb-scripts namespace="user">
	<default>
		<script name="querUser">
			<sql>
				<![CDATA[
					select * from  user
					where 1=1 
					<#if name?exists&&name.isNotEmpty()>
						and name='${name}'
					</#if>
				]]>
			</sql>
			<parameters>
			<parameter name="name" datatype="string"/>

			</parameters>
		</script>
		<script name="querUser2">
			<sql>
				<![CDATA[
					select * from  user
					where 1=1 
					and name=?
				]]>
			</sql>
			<parameters>
			<parameter name="name" datatype="string"/>
			</parameters>
		</script>
	</default>
</compactdb-scripts>
