=== wangyoushun/CompactDb/src/com/six/compactdb/dtd/compactdb-configuration-1.0.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!-- CompactDb configuration configuration document.

<!DOCTYPE compactdb-configuration PUBLIC
    "-//compactdb/compactdb Script DTD 1.0//EN"
    "http://www.iwantfly.sh.cn/compactdb-configuration-1.0.dtd" >
-->
<!ELEMENT compactdb-configuration (compactdb?, databases)>
<!ELEMENT compactdb (properties?)>
<!ELEMENT databases (database+)>

<!ELEMENT database (properties?, tables?, scripts?)>
<!ATTLIST database
	name CDATA #REQUIRED
>
<!ELEMENT properties (property*)>
<!ATTLIST properties
	reference CDATA #IMPLIED
>
<!ELEMENT property (#PCDATA)>
<!ATTLIST property
	name CDATA #REQUIRED
>
<!ELEMENT scripts (script*)>
<!ELEMENT script EMPTY>
<!ATTLIST script
	resource CDATA #REQUIRED
>
<!ELEMENT tables (table*)>
<!ELEMENT table EMPTY>
<!ATTLIST table
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	keygen (assign | identity | uuid | sequence) "assign"
	sequence CDATA #IMPLIED
>

=== wangyoushun/CompactDb/test/compactDbConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE compactdb-configuration PUBLIC
    "-//compactdb/compactdb Script DTD 1.0//EN"
    "http://www.iwantfly.sh.cn/compactdb-configuration-1.0.dtd" >
    
<compactdb-configuration>
	<compactdb>
		<properties>
			<property name="compactdb.showsql">true</property>
			<property name="compactdb.resource.reload">false</property>
		</properties>
	</compactdb>
	
	<databases>
		<database name="default">
			<properties>
				<!-- 参数配置 -->
				<property name="compactdb.database.type">mysql</property>
				<property name="compactdb.database.connection.driverclass">com.mysql.jdbc.Driver</property>
				<property name="compactdb.database.connection.url">jdbc:mysql://localhost:3306/mybatis</property>
				<property name="compactdb.database.connection.user">root</property>
				<property name="compactdb.database.connection.password">root</property>
				<property name="compactdb.database.c3p0.poolsize">4</property>
				<property name="compactdb.database.c3p0.maxidletime">0</property>
			</properties>
			
			<tables>
				<!-- 根据主键操作表 配置-->
				<table id="user" name="user"  />
			</tables>
			<scripts>
			<!-- 查询资源 -->
			<script resource="user.xml" />
			</scripts>
		</database>
	</databases>
</compactdb-configuration>
